### ISSUE TITLE
distribution plot (2nd plot)

### ISSUE THREAD

**Issue by katterris** [ropenscilabs/smoky#10]
This if for volunteers to work on the distribution plot (2nd plot)

https://isithotrightnow.com/#detail

**Comment by ekothe** [comment]
Happy to start work on this

![image](https://user-images.githubusercontent.com/11023525/70677223-a84c9800-1ce2-11ea-8505-ba0ec301b577.png)

Need to be able to 
- [x] Filter data for observations for +/- 7 days around Sys.date()
- [x] Collapse observations from the same day on different years
- [x] Find percentiles
- [x] Plot 25th, 50th, and 75th percentiles as vlines
- [x] Plot current observation as vline
- [x] Plot distribution using a density(?) plot

**Comment by ekothe** [comment]
Current version looks like this

![image](https://user-images.githubusercontent.com/11023525/70682963-a12e8580-1cf4-11ea-8c22-258001dda1ca.png)
Would appreciate help with annotating the vertical lines...
