### ISSUE TITLE
Yearly plot (3rd plot)

### ISSUE THREAD

**Issue by katterris** [ropenscilabs/smoky#11]
This if for volunteers to work on the yearly plot (3rd plot)

https://isithotrightnow.com/#detail

**Comment by jenrichmond** [comment]
<img width="1280" alt="Screenshot 2019-12-12 13 58 49" src="https://user-images.githubusercontent.com/40267093/70678929-aa652580-1ce7-11ea-837b-a295194348fc.png">


We are aiming for this... grid, maybe image function will help?

**Comment by Maschette** [comment]
So there are two parts to this assuming we have the the data: 
- [ ] 1  create an array which stores the daily percentiles for this year
- [ ] 1.1 for each day, pull the data out for each day across years and work out the percentile for each day. 
- [ ] 2 plot it.
