### ISSUE TITLE
gganimate code not working

### ISSUE THREAD

**Issue by jenrichmond** [ropenscilabs/smoky#39]
hi @JohnOrmerod I downloaded the data from nswgov as of 19/12/23 and managed to regenerate the grid plot with it, but the animation code wouldn't run for me. Not sure if you had pushed the latest versions of your code to git, no hurry obviously 🎄 🎅 happy holidays! Jen

**Comment by JohnOrmerod** [comment]
Hey @jenrichmond. Will try to figure out why tonight. We are at stage 2. on my t-shirt "It works on my computer". Happy holidays Jen and I hope you are having a break. John

**Comment by JohnOrmerod** [comment]
Hi @jenrichmond. It might be a version thing. Can you run each chunk in smoky_john2.Rmd ?
There is a line with the code:
devtools::session_info()

which will spit out all of the packages and package versions that were used. Mine returns
the output below. Can you have a look to see if there is a difference in package/R versions? It is probably that.
Kind regards,
John


- Session info ---------------------------------------------------------

- Packages -------------------------------------------------------------
 package      * version date       lib source        
 assertthat     0.2.1   2019-03-21 [1] CRAN (R 3.6.0)
 backports      1.1.5   2019-10-02 [1] CRAN (R 3.6.1)
 broom          0.5.2   2019-04-07 [1] CRAN (R 3.6.0)
 callr          3.3.2   2019-09-22 [1] CRAN (R 3.6.1)
 cellranger     1.1.0   2016-07-27 [1] CRAN (R 3.6.0)
 cli            1.1.0   2019-03-19 [1] CRAN (R 3.6.0)
 colorspace     1.4-1   2019-03-18 [1] CRAN (R 3.6.0)
 crayon         1.3.4   2017-09-16 [1] CRAN (R 3.6.0)
 desc           1.2.0   2018-05-01 [1] CRAN (R 3.6.0)
 devtools       2.2.1   2019-09-24 [1] CRAN (R 3.6.1)
 digest         0.6.22  2019-10-21 [1] CRAN (R 3.6.1)
 dplyr        * 0.8.3   2019-07-04 [1] CRAN (R 3.6.1)
 ellipsis       0.3.0   2019-09-20 [1] CRAN (R 3.6.1)
 extrafont      0.17    2014-12-08 [1] CRAN (R 3.6.0)
 extrafontdb    1.0     2012-06-11 [1] CRAN (R 3.6.0)
 fansi          0.4.0   2018-10-05 [1] CRAN (R 3.6.0)
 farver         1.1.0   2018-11-20 [1] CRAN (R 3.6.0)
 forcats      * 0.4.0   2019-02-17 [1] CRAN (R 3.6.0)
 fs             1.3.1   2019-05-06 [1] CRAN (R 3.6.1)
 generics       0.0.2   2018-11-29 [1] CRAN (R 3.6.0)
 gganimate    * 1.0.3   2019-04-02 [1] CRAN (R 3.6.0)
 ggplot2      * 3.2.1   2019-08-10 [1] CRAN (R 3.6.1)
 gifski         0.8.6   2018-09-28 [1] CRAN (R 3.6.1)
 glue           1.3.1   2019-03-12 [1] CRAN (R 3.6.0)
 gridExtra      2.3     2017-09-09 [1] CRAN (R 3.6.0)
 gtable         0.3.0   2019-03-25 [1] CRAN (R 3.6.0)
 haven          2.1.0   2019-02-19 [1] CRAN (R 3.6.0)
 here         * 0.1     2017-05-28 [1] CRAN (R 3.6.0)
 hms            0.5.1   2019-08-23 [1] CRAN (R 3.6.1)
 httr           1.4.0   2018-12-11 [1] CRAN (R 3.6.0)
 janitor      * 1.2.0   2019-04-21 [1] CRAN (R 3.6.1)
 jsonlite       1.6     2018-12-07 [1] CRAN (R 3.6.0)
 knitr          1.24    2019-08-08 [1] CRAN (R 3.6.1)
 labeling       0.3     2014-08-23 [1] CRAN (R 3.6.0)
 lattice        0.20-38 2018-11-04 [2] CRAN (R 3.6.1)
 lazyeval       0.2.2   2019-03-15 [1] CRAN (R 3.6.0)
 lifecycle      0.1.0   2019-08-01 [1] CRAN (R 3.6.1)
 lubridate    * 1.7.4   2018-04-11 [1] CRAN (R 3.6.0)
 magrittr       1.5     2014-11-22 [1] CRAN (R 3.6.0)
 memoise        1.1.0   2017-04-21 [1] CRAN (R 3.6.0)
 modelr         0.1.4   2019-02-18 [1] CRAN (R 3.6.0)
 munsell        0.5.0   2018-06-12 [1] CRAN (R 3.6.0)
 nlme           3.1-140 2019-05-12 [2] CRAN (R 3.6.1)
 packrat        0.5.0   2018-11-14 [1] CRAN (R 3.6.0)
 pillar         1.4.2   2019-06-29 [1] CRAN (R 3.6.1)
 pkgbuild       1.0.6   2019-10-09 [1] CRAN (R 3.6.1)
 pkgconfig      2.0.3   2019-09-22 [1] CRAN (R 3.6.1)
 pkgload        1.0.2   2018-10-29 [1] CRAN (R 3.6.0)
 plyr           1.8.4   2016-06-08 [1] CRAN (R 3.6.0)
 png            0.1-7   2013-12-03 [1] CRAN (R 3.6.0)
 prettyunits    1.0.2   2015-07-13 [1] CRAN (R 3.6.0)
 processx       3.4.1   2019-07-18 [1] CRAN (R 3.6.1)
 progress       1.2.0   2018-06-14 [1] CRAN (R 3.6.0)
 ps             1.3.0   2018-12-21 [1] CRAN (R 3.6.0)
 purrr        * 0.3.2   2019-03-15 [1] CRAN (R 3.6.0)
 R6             2.4.0   2019-02-14 [1] CRAN (R 3.6.0)
 RColorBrewer   1.1-2   2014-12-07 [1] CRAN (R 3.6.0)
 Rcpp           1.0.2   2019-07-25 [1] CRAN (R 3.6.1)
 readr        * 1.3.1   2018-12-21 [1] CRAN (R 3.6.0)
 readxl       * 1.3.1   2019-03-13 [1] CRAN (R 3.6.1)
 remotes        2.1.0   2019-06-24 [1] CRAN (R 3.6.1)
 rlang          0.4.0   2019-06-25 [1] CRAN (R 3.6.1)
 rprojroot      1.3-2   2018-01-03 [1] CRAN (R 3.6.0)
 rstudioapi     0.10    2019-03-19 [1] CRAN (R 3.6.0)
 Rttf2pt1       1.3.7   2018-06-29 [1] CRAN (R 3.6.0)
 rvest          0.3.3   2019-04-11 [1] CRAN (R 3.6.0)
 scales         1.0.0   2018-08-09 [1] CRAN (R 3.6.0)
 sessioninfo    1.1.1   2018-11-05 [1] CRAN (R 3.6.0)
 snakecase      0.11.0  2019-05-25 [1] CRAN (R 3.6.1)
 stringi        1.4.3   2019-03-12 [1] CRAN (R 3.6.0)
 stringr      * 1.4.0   2019-02-10 [1] CRAN (R 3.6.1)
 testthat       2.2.1   2019-07-25 [1] CRAN (R 3.6.1)
 tibble       * 2.1.3   2019-06-06 [1] CRAN (R 3.6.1)
 tidyr        * 1.0.0   2019-09-11 [1] CRAN (R 3.6.1)
 tidyselect     0.2.5   2018-10-11 [1] CRAN (R 3.6.0)
 tidyverse    * 1.2.1   2017-11-14 [1] CRAN (R 3.6.1)
 tweenr         1.0.1   2018-12-14 [1] CRAN (R 3.6.0)
 usethis        1.5.0   2019-04-07 [1] CRAN (R 3.6.0)
 utf8           1.1.4   2018-05-24 [1] CRAN (R 3.6.0)
 vctrs          0.2.0   2019-07-05 [1] CRAN (R 3.6.1)
 waffle       * 0.7.0   2017-01-07 [1] CRAN (R 3.6.1)
 withr          2.1.2   2018-03-15 [1] CRAN (R 3.6.0)
 xfun           0.9     2019-08-21 [1] CRAN (R 3.6.1)
 xml2           1.2.0   2018-01-24 [1] CRAN (R 3.6.0)
 zeallot        0.1.0   2018-01-28 [1] CRAN (R 3.6.0)

[1] C:/Users/jormerod/Documents/R/win-library/3.6
[2] C:/Program Files/R/R-3.6.1/library
