### ISSUE TITLE
Find equivalent data sources from each state/territory

### ISSUE THREAD

**Issue by ekothe** [ropenscilabs/smoky#5]
@leasdale - could you give us the list of columns from the NSW dataset?

**Comment by jenrichmond** [comment]
NSW gov site gives you the impression you can choose to download different metrics, but it wont you let you click so only downloads AQI

https://www.dpie.nsw.gov.au/air-quality/search-for-and-download-air-quality-data

**Comment by jenrichmond** [comment]
the waqi site pulls Nth Territory data from

Air Quality Data provided by NTEPA - Northen Territory Environment Protection Authority (ntepa.nt.gov.au)

**Comment by jenrichmond** [comment]
the waqi site pulls Tasmania data from

Air Quality Data provided by EPA Tasmania - Tasmania Environment Protection Authority (epa.tas.gov.au)

**Comment by leasdale** [comment]
the waqi site pulles QLD data from
Air Quality Data provided by the Air quality | Environment, land and water | Queensland Government (qld.gov.au)

**Comment by jenrichmond** [comment]
the waqi site gets Sth Australia from here

http://www.epa.sa.gov.au/data_and_publications/air_quality_monitoring

**Comment by jenrichmond** [comment]
the waqi for victoria is here 

Air Quality Data provided by the Environment Protection Authority | EPA Victoria (epa.vic.gov.au)

**Comment by jenrichmond** [comment]
> the waqi site pulls Nth Territory data from
> 
> Air Quality Data provided by NTEPA - Northen Territory Environment Protection Authority (ntepa.nt.gov.au)

**Comment by katterris** [comment]
ACT data is here
https://www.health.act.gov.au/about-our-health-system/population-health/environmental-monitoring/monitoring-and-regulating-air
