### ISSUE TITLE
Generated text

### ISSUE THREAD

**Issue by katterris** [ropenscilabs/smoky#8]
This if for volunteers to work on the generated text

https://isithotrightnow.com/#detail

**Comment by ekothe** [comment]
The text in the example is as follows

> "Today's maximum temperature so far is 22.7°C, and the minimum overnight was 18.6°C. The average of the two is 20.65 °C , which is hotter than 42% of daily average temperatures at Observatory Hill for this time of year over the period 1910–2017. The really hot and cold days (top and bottom 5%, respectively) are outside the dotted lines."

Given that the available data is actually a 24 hour observation rather than hourly, I wonder whether it would make sense to reframe with weekly information. 

Anyone else have thoughts?

**Comment by katterris** [comment]
Dani and I will be working on the text.
Will re-frame with weekly information
